Add raft_uv_tcp_set_bind_address().
canonical/raft pull request #274
Opened 2022-04-07 08:55 UTC by ralight

This allows an application to choose which network interface the
listening socket will bind to.

Closes #273.

Signed-off-by: Roger A. Light <roger@atchoo.org>

2022-04-07 11:30 UTC, MathieuBordere requested changes
Hi, thanks for this!

Could you fix the memory leak and add a basic test for this in https://github.com/canonical/raft/blob/master/test/integration/test_uv_tcp_listen.c ?

2022-04-07 11:30 UTC, MathieuBordere commented on src/uv_tcp.c
> +    t->bind_address = strdup(address);
This memory is never freed, we also usually use the allocator functions from `src/heap.c`, you could do something similar as here https://github.com/canonical/raft/blob/3769e75e5adbb6954c557403818cb53cc9aa14e1/src/raft.c#L44

2022-04-07 12:27 UTC, ralight commented
Thanks. I've fixed the memory, but could do with a hint on what you'd like out of the test? I could repeat the `/* If the handshake is successful, the accept callback is invoked. */` test, but with a custom `setUp()` function?

2022-04-07 13:09 UTC, MathieuBordere commented
> Thanks. I've fixed the memory, but could do with a hint on what you'd like out of the test? I could repeat the `/* If the handshake is successful, the accept callback is invoked. */` test, but with a custom `setUp()` function?

Yes, that would be fine. I see that the call to `raft_init` is buried pretty deep in the test setup and you would probably need to touch a lot of code to make it work, I'm not sure if it's worth it. @freeekanayaka What do you think?

2022-04-12 18:03 UTC, ralight commented
I've added a test which covers the call. It's not especially satisfactory, let me know what you think.

2022-04-13 06:19 UTC, merged