Add raft_voter_contact()
canonical/raft pull request #492
Opened 2024-01-25 20:08 UTC by ralight

This returns the number of voting nodes that are recently in contact with the leader, to allow determining if the cluster is currently in a degraded / at risk state.

I'd be interested on your thoughts on this. At the moment it feels like not being able to find out this information is an omission.

2024-01-25 20:59 UTC, cole-miller commented
Not speaking for the rest of the team, but this seems reasonable to me. I would like a note in the docstring that the return value is not to be relied on for correctness (since it could be out of date), and a couple of tests.

2024-01-25 21:03 UTC, cole-miller requested changes

2024-01-25 21:03 UTC, cole-miller commented on include/raft.h
> +            uint32_t voter_contacts;        /* Current number of voting nodes we are in contact with */
Please initialize this explicitly to 0 in raft_init, and reset it to 1 when entering leader state. (Without the second part, raft_voter_contacts could return a stale value from a previous term.)

2024-01-25 22:30 UTC, ralight commented
@cole-miller Thanks for the feedback. I've added the initialisation to 0 on init, reset to 1 on changing to a leader, and added a test which starts off with 3 nodes, kills off a node, and revives the node, with checks at each step. If you'd like more tests please give me some hints on the direction to go in.

2024-01-29 15:09 UTC, MathieuBordere approved these changes
Thanks for this, seems useful.

2024-01-29 15:11 UTC, cole-miller approved these changes
Thanks!

2024-01-29 15:11 UTC, merged